using System.CommandLine;
using S1Atlas.Cli.Output;
using S1Atlas.Core.Storage;
using S1Atlas.Indexing.Scene;

namespace S1Atlas.Cli.Commands;

internal static class SceneCommandSupport
{
    public static Option<int> CreateLimitOption() => new("--limit") { DefaultValueFactory = _ => SceneQueryService.DefaultLimit, Description = "Maximum number of returned rows." };
    public static int Run(string name, bool json, TextWriter output, TextWriter error, CancellationToken cancellationToken, IAtlasRepository repository, Func<int> action) => CommandExecution.Run(() => { repository.InitializeAsync(cancellationToken).GetAwaiter().GetResult(); return action(); }, new CommandOutput(name, json, output, error), cancellationToken);
    public static int Write<T>(CommandOutput output, T data, (string Code, string Message)? failure, Action<TextWriter> human) => failure is null ? output.Success(data, human) : output.FailureWithData(failure.Value.Code, failure.Value.Message, data, human);
    public static (string Code, string Message)? FailureFor(SceneQueryStatus status) => status switch { SceneQueryStatus.NoCompletedSceneIndex => ("NoCompletedSceneIndex", "No completed scene index exists for the requested build."), SceneQueryStatus.SceneSnapshotNotFound => ("SceneSnapshotNotFound", "The requested scene snapshot was not found."), SceneQueryStatus.SceneNotFound => ("SceneNotFound", "No indexed scene matched the selector."), SceneQueryStatus.AmbiguousScene => ("AmbiguousScene", "The scene selector matched multiple candidates. Use an exact scene ID."), SceneQueryStatus.GameObjectNotFound => ("GameObjectNotFound", "No indexed game object matched the selector."), SceneQueryStatus.AmbiguousGameObject => ("AmbiguousGameObject", "The game object selector matched multiple candidates. Use an exact game object ID."), SceneQueryStatus.ComponentNotFound => ("ComponentNotFound", "No indexed component matched the selector."), SceneQueryStatus.AmbiguousComponent => ("AmbiguousComponent", "The component selector matched multiple candidates. Use an exact component ID."), SceneQueryStatus.UnresolvedCodeSymbol => ("UnresolvedCodeSymbol", "The component has no exact resolved code symbol."), SceneQueryStatus.PartialRecovery => ("PartialRecovery", "The selected scene data is partially recovered."), SceneQueryStatus.UnresolvedSceneReference => ("UnresolvedSceneReference", "The selected scene data contains unresolved references."), _ => null };
    public static string ContainerText(string id, IReadOnlyList<S1Atlas.Core.Scenes.SceneContainerRecord>? containers) { var container = containers?.SingleOrDefault(row => row.ContainerId == id); return container is null ? $"container metadata unavailable | id {id}" : $"{container.RelativePath} | sha256 {container.Sha256} | sidecar {container.SidecarManifest}"; }
    public static void WriteScene(SceneDocumentOutput data, TextWriter writer) { WriteSnapshot(data.Snapshot, writer); if (data.Scene is not null) writer.WriteLine($"Scene: {data.Scene.Kind} | {data.Scene.Name} | {data.Scene.SceneId} | local {data.Scene.SourceLocalFileId} | objects {data.Scene.ObjectCount} | roots {data.Scene.RootCount} | {ContainerText(data.Scene.ContainerId, data.Containers)} | {data.Scene.RecoveryStatus}"); foreach (var candidate in data.Candidates) writer.WriteLine($"Candidate: {candidate.Name} | {candidate.SceneId} | {ContainerText(candidate.ContainerId, data.Containers)} | {candidate.RecoveryStatus}"); WritePages(data.Children, data.Components, data.References, data.Containers, writer); }
    public static void WriteGameObject(GameObjectOutput data, TextWriter writer) { WriteSnapshot(data.Snapshot, writer); if (data.GameObject is not null) writer.WriteLine($"GameObject: {data.GameObject.Name} | {data.GameObject.GameObjectId} | scene {data.GameObject.SceneId} | local {data.GameObject.LocalFileId} | active {data.GameObject.Active} | layer {data.GameObject.Layer} | tag {data.GameObject.Tag} | {ContainerText(data.GameObject.ContainerId, data.Containers)} | {data.GameObject.RecoveryStatus}"); foreach (var candidate in data.Candidates) writer.WriteLine($"Candidate: {candidate.Name} | {candidate.GameObjectId} | {ContainerText(candidate.ContainerId, data.Containers)} | {candidate.RecoveryStatus}"); WritePages(data.Children, data.Components, data.References, data.Containers, writer); }
    public static void WriteComponent(ComponentOutput data, TextWriter writer) { WriteSnapshot(data.Snapshot, writer); if (data.Component is not null) writer.WriteLine($"Component: {data.Component.Kind} | {data.Component.ComponentId} | object {data.Component.GameObjectId} | local {data.Component.LocalFileId} | class {data.Component.UnityClassId} | script {data.Component.ScriptAssembly}/{data.Component.ScriptNamespace}.{data.Component.ScriptClass} | {ContainerText(data.Component.ContainerId, data.Containers)} | symbol {data.Component.ResolvedTypeSymbolId ?? "unresolved"} | index {data.Component.ResolvedCodeIndexId ?? "unresolved"} | {data.Component.TypeResolutionStatus} | {data.Component.RecoveryStatus}"); if (data.CodeSymbol is not null) writer.WriteLine($"Code: {data.CodeSymbol.QualifiedName} | {data.CodeSymbol.Signature} | {data.CodeSymbol.SymbolId} | index {data.CodeSymbol.IndexId}"); foreach (var candidate in data.Candidates) writer.WriteLine($"Candidate: {candidate.Kind} | {candidate.ComponentId} | {ContainerText(candidate.ContainerId, data.Containers)} | {candidate.RecoveryStatus}"); WriteReferences(data.References, data.Containers, writer); }
    private static void WriteSnapshot(S1Atlas.Core.Scenes.SceneSnapshotRecord? snapshot, TextWriter writer) { if (snapshot is not null) writer.WriteLine($"Snapshot: {snapshot.SceneSnapshotId} | build {snapshot.BuildId} | extraction {snapshot.ExtractionId} | code snapshot {snapshot.CodeSnapshotId} | index {snapshot.CodeIndexId} | parser {snapshot.ParserId} {snapshot.ParserVersion} | recovery {snapshot.RecoveryStatus}"); }
    private static void WritePages(S1Atlas.Core.Scenes.ScenePageResult<S1Atlas.Core.Scenes.SceneGameObjectRecord> children, S1Atlas.Core.Scenes.ScenePageResult<S1Atlas.Core.Scenes.SceneComponentRecord> components, S1Atlas.Core.Scenes.ScenePageResult<S1Atlas.Core.Scenes.SceneReferenceRecord> references, IReadOnlyList<S1Atlas.Core.Scenes.SceneContainerRecord>? containers, TextWriter writer) { writer.WriteLine($"Children: total {children.TotalCount} | returned {children.ReturnedCount}"); foreach (var child in children.Rows) writer.WriteLine($"Child: {child.Name} | id {child.GameObjectId} | scene {child.SceneId} | local {child.LocalFileId} | active {child.Active} | layer {child.Layer} | tag {child.Tag} | {ContainerText(child.ContainerId, containers)} | recovery {child.RecoveryStatus}"); writer.WriteLine($"Components: total {components.TotalCount} | returned {components.ReturnedCount}"); foreach (var component in components.Rows) writer.WriteLine($"Component: {component.Kind} | id {component.ComponentId} | object {component.GameObjectId} | local {component.LocalFileId} | class {component.UnityClassId} | script {component.ScriptAssembly}/{component.ScriptNamespace}.{component.ScriptClass} | {ContainerText(component.ContainerId, containers)} | symbol {component.ResolvedTypeSymbolId ?? "unresolved"} | index {component.ResolvedCodeIndexId ?? "unresolved"} | resolution {component.TypeResolutionStatus} | recovery {component.RecoveryStatus}"); WriteReferences(references, containers, writer); }
    private static void WriteReferences(S1Atlas.Core.Scenes.ScenePageResult<S1Atlas.Core.Scenes.SceneReferenceRecord> references, IReadOnlyList<S1Atlas.Core.Scenes.SceneContainerRecord>? containers, TextWriter writer) { writer.WriteLine($"References: total {references.TotalCount} | returned {references.ReturnedCount} | unresolved {references.UnresolvedCount}"); foreach (var reference in references.Rows) writer.WriteLine($"Reference: id {reference.ReferenceId} | source component {reference.SourceComponentId ?? "none"} | field {reference.FieldPath ?? "none"} | declared {reference.DeclaredType ?? "none"} | source local {reference.SourceLocalFileId} | source {ContainerText(reference.SourceContainerId, containers)} | target container {(reference.TargetContainerId is null ? "none" : ContainerText(reference.TargetContainerId, containers))} | target local {reference.TargetLocalFileId?.ToString() ?? "none"} | target object {reference.TargetGameObjectId ?? "none"} | target component {reference.TargetComponentId ?? "none"} | target symbol {reference.TargetSymbolId ?? "none"} | target text {reference.TargetText ?? "none"} | evidence {reference.Evidence} | resolution {reference.ResolutionStatus} | recovery {reference.RecoveryStatus}"); }
}
