<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\S1Atlas.Application\S1Atlas.Application.csproj" />
    <ProjectReference Include="..\S1Atlas.Core\S1Atlas.Core.csproj" />
    <ProjectReference Include="..\S1Atlas.Indexing\S1Atlas.Indexing.csproj" />
    <ProjectReference Include="..\S1Atlas.Storage\S1Atlas.Storage.csproj" />
  </ItemGroup>
</Project>
